#!/bin/ash

exec > /dev/kmsg 2>&1

echo
echo "Yay, booted"
echo
mount -t proc /proc /proc
mount -t sysfs none /sys
mount -n -o mode=0620,gid=5 -t devpts devpts /dev/pts
echo mounted
cat /proc/cpuinfo
cat /proc/interrupts
/bin/start_tunnel.sh
ifconfig -a
ps faux | grep tunnel | grep -v grep || echo none 2>&1 > /dev/kmsg
free -m
telnetd -l /bin/bash
