#!/bin/ash

mkdir /dev
mknod -m 622 /dev/kmsg c 1 11
exec > /dev/kmsg 2>&1

#mknod -m 622 /dev/console c 5 1
mknod -m 622 /dev/mem c 1 1
mkdir /dev/net/
mknod -m 666 /dev/net/tun c 10 200
mknod -m 666 /dev/null c 1 3
mknod -m 666 /dev/ptmx c 5 2
mkdir /dev/pts
mknod -m 444 /dev/random c 1 8
mknod -m 666 /dev/tty c 5 0
mknod -m 666 /dev/tty0 c 4 0
mknod -m 666 /dev/ttyS0 c 4 64
mknod -m 666 /dev/ttyS1 c 4 65
mknod -m 444 /dev/urandom c 1 9
mknod -m 666 /dev/zero c 1 5

mkdir /proc
mkdir /sys

echo
echo "Yay, booted"
echo
mount -t proc /proc /proc
mount -t sysfs none /sys
mount -n -o mode=0620,gid=5 -t devpts devpts /dev/pts
echo mounted
cat /proc/cpuinfo
cat /proc/interrupts
/bin/start_tunnel.sh
ifconfig -a
ps faux | grep tunnel | grep -v grep || echo none 2>&1 > /dev/kmsg
free -m
telnetd -l /bin/bash
insmod /kmod/rpmsg.ko
insmod /kmod/client_rpmsg.ko
mknod -m 666 /dev/crpmsg0 c 252 0
