obj-$(CONFIG_RPMSG)		+= rpmsg.o
rpmsg-y				:= virtio_rpmsg_bus.o remoteproc_rpmsg.o dummy_rpmsg_lproc.o rpmsg_dma_pool.o
obj-$(CONFIG_RPMSG_CLIENT)	+= rpmsg_client.o
rpmsg_client-y			:= rpmsg_client.o
rpmsg_client-y			+= rpmsg_client_ping.o
