obj-$(CONFIG_RPMSG)		+= rpmsg.o
rpmsg-y				:= virtio_rpmsg_bus.o remoteproc_rpmsg.o dummy_rpmsg_lproc.o
obj-$(CONFIG_RPMSG_CLIENT)	+= client_rpmsg.o
client_rpmsg-y			:= rpmsg_client.o
client_rpmsg-y			+= rpmsg_client_ping.o
